- name: Play level variables
  hosts: local
  connection: local #Ansible is connecting to localhost
  vars: 
    COURSE: Ansible
    DURATION: 10HRS
    Trainer: Sunny
  tasks:
  - name: Print the Info
    vars:
      COURSE: Terraform
    ansible.builtin.debug:
      msg: "Name is {{ COURSE }}, Duration: {{ DURATION }}, Trainer {{ Trainer }} "   