- name: Prompting Variables
  hosts: local
  connection: local
  vars_prompt:
    - name: username
      prompt: What is your username?
      private: false

    - name: password
      prompt: What si your password?

  tasks:
    - name: Print a message
      ansible.builtin.debug:
        msg: 'Logging in as {{ username }}'      