- name: Transforming String into lists
  hosts: local
  connection: local
  vars: 
    listjojo: BMW, Guru, Roku, Sage #String  
    tags: # Map == Dictionary
      Application: payment
      Environment: dev
    listTags:
      - key: Application
        value: payment
      - key: Environment
        value: dev   
  tasks:
  - name: Convert String to list
    ansible.builtin.debug:
      msg: "{{ listjojo | split(', ') }}"

  - name: Convert Map to list
    ansible.builtin.debug:
      msg: "{{ tags | dict2items }}"
