- name: Transforming String into lists
  hosts: local
  connection: local
  vars:
    listjojo: BMW, Guru, Roku, Sage   # String
    name: "Sunny"
    gmail: Sunny@GMAIL.COM
    IP_Addr: 255.255.255.255
    tags:                             # Map == Dictionary
      Application: payment
      Environment: dev
    listTags:                         # List
      - key: Application
        value: payment
      - key: Environment
        value: dev

  tasks:
    - name: Convert String to list
      ansible.builtin.debug:
        msg: "{{ listjojo | split(', ') }}"

    - name: Convert Map to list
      ansible.builtin.debug:
        msg: "{{ tags | dict2items }}"

    - name: Convert list to Map
      ansible.builtin.debug:
        msg: "{{ listTags | items2dict }}"

    - name: Read YAML and take it into variable
      ansible.builtin.set_fact:
        student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml }}"

    - name: Convert YAML into JSON
      ansible.builtin.debug:
        msg: "{{ student_yaml | to_nice_json }}"

    - name: Save JSON to file
      ansible.builtin.copy:
        dest: ./student-data.json
        content: "{{ student_yaml | to_nice_json }}"
      
    - name: Convert Uppercase
      ansible.builtin.debug:
        msg: "{{ name | upper }}"

    - name: Convert Lowercase
      ansible.builtin.debug:
        msg: "{{ name | lower }}"

    - name: Validate IP Address
      ansible.builtin.debug:
        msg: "{{ IP_Addr | ansible.utils.ipv4 }}"    

    - name: grep the root
      ansible.builtin.shell: cat /etc/passwd | grep root
      register: command_output

    - name: print the command_output
      ansible.builtin.debug:
        msg: "{{ command_output }}"    

    - name: redirect the output
      ansible.builtin.command: ls -ltr
        register: redirect_output    

    - name: print the redirected output
      ansible.builtin.debug:
        msg: "{{ redirect_output }}"    