- name: User Creation
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id roboshop
    register: command_output
    ignore_errors: true

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ command_output }}"  